### ISSUE TITLE
Release on F-droid

### ISSUE THREAD

**Issue by aha999** [meditohq/medito-app#195] opened 2021-08-24 20:41 UTC
I think that this app should be released on F-droid, which is an open source app-store for FOSS apps and it could lead into more contributors.

It's also privacy respecting and builds apps from source code, so it guarantees app  transparency.

Also i prefer apps from f-droid because of privacy reasons and distancing from Google when possible.

<a href="https://dashboard.polar.sh/meditohq/medito-app/issues/195">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/meditohq/medito-app/issues/195/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/meditohq/medito-app/issues/195/pledge.svg">
</picture>
</a>

**Comment by IzzySoft** [comment] 2021-11-03 14:05
Until you're ready for "F-Droid proper" (which e.g. doesn't accept Firebase): there was [a request](https://gitlab.com/IzzyOnDroid/repo/-/issues/208) to include your app with my repo. If you could make the APK files available (ideally attached to their corresponding releases here; starting with the latest one fully suffices) I could look into that. This would provide a stepping stone on the way to the final goal of this issue :smiley:

**Comment by michaelcspeed** [comment] 2022-01-11 14:42
We would love to release the app on FDroid, we just have a few issues to work through first.
We need to find an open source Firebase alternative, which at the moment I'm fairly sure we only use for cloud messaging.
If someone could also post the other requirements here and whether or not we meet them (I can also chime in for this) that would be great 👍

**Comment by aha999** [comment] 2022-01-11 15:00
@michaelcspeed take a look at [Supabase](https://supabase.com/)

**Comment by IzzySoft** [comment] 2022-01-11 16:08
> we only use for cloud messaging.

Woah. Perfect alternative to that would be @unifiedpush – see e.g. [here](https://gitlab.com/-/snippets/1896503#push) and [here](https://android.izzysoft.de/applists/category/named/network_push). Can even fall back to Firebase for your Play releases if you want it to. Else it simply leaves the choice with the user whether they want notifications via Gotify, Nextcloud, ntfy…

Until then, let me repeat my offer from last November: if you'd provide the APK, it could go to [my repo](https://apt.izzysoft.de/fdroid) immediately until you're ready for the stricter requirements of F-Droid.org.

**Comment by IzzySoft** [comment] 2022-04-02 20:20
Had you any chance to take look, @michaelcspeed? The [request for F-Droid inclusion](https://gitlab.com/fdroid/rfp/-/issues/1850) i still waiting for this. If neither Supabase nor UnifiedPush satisfied your wishes, here's one more Firebase replacement: [appwrite](https://github.com/appwrite/appwrite). And the offer with my repo is still standing, too :smile:

**Comment by CodeCubeNeo** [comment] 2022-04-28 11:54
Any updates on this?

**Comment by IzzySoft** [comment] 2022-04-28 18:47
I'm still waiting for the APK to show up :wink:

**Comment by ghost** [comment] 2022-05-05 10:45
The APKs are visible

**Comment by IzzySoft** [comment] 2022-05-13 06:30
> The APKs are visible

Now you just need to define where. I've looked [at the releases](https://github.com/meditohq/medito-app/releases), there are none. I've looked in the repo and saw none either. So where are they visible?

@michaelcspeed Any progress I can report back to F-Droid? The RFP is entering the candidate-to-close status now as there was no update for another month. One more month and it will be closed due to inactivity.

**Comment by ghost** [comment] 2022-05-15 06:47
>> I've looked [at the releases](https://github.com/meditohq/medito-app/releases), there are none.

I didn't notice that there are no APKs in the releases, my bad. Sorry about that.

**Comment by IzzySoft** [comment] 2022-05-15 20:00
Happens :smile: Just let me know when an APK is available there (I hope I'll get the ping then; currently it seems Github notifications no longer reach my mailbox).

**Comment by michaelcspeed** [comment] 2022-05-26 13:50
@IzzySoft APK is now available here https://github.com/meditohq/medito-app/releases, and new versions will be automatically uploaded there too.

We have removed the Firebase libraries, so we are one step closer to FDroid too :)

**Comment by IzzySoft** [comment] 2022-05-27 00:21
Thanks! I've just added it to my repo now, as my scanner confirmed. I see you're using Sentry now. Have you configured it opt-in, or is it enabled by default? Do you self-host the server part?

One more thing I wonder is that Play says the app is just 3.5M while the APK is rather close to 30M. Did that change recently? Note that the size limit in my repo is 30M per app, so I cannot keep multiple versions at this size. But with some luck your app will be at F-Droid before the single APK exceeds that limit :smile:

**Comment by michaelcspeed** [comment] 2022-05-27 10:24
We have been using Sentry for a while, yes. It's enabled for everyone but maybe that's something we should think about. We don't self-host it. You can read about privacy notice here https://docs.sentry.io/product/security/mobile-privacy/ and here https://sentry.io/privacy/

The APK contains all the configurations for all phone types, which is why it is much larger. The package hosted on the Play Store is an AAB, which is customised to your device. As far as I know it's not possible to directly install an AAB on your device without the Play Store.

**Comment by IzzySoft** [comment] 2022-05-27 12:03
Thanks! So for now the app is flagged "Tracking" (due to Sentry being enabled by default). Once you've made it opt-in please drop me a note so I can drop that anti-feature (an white-list your Sentry).

As for APK-size: I should have guessed; yes, that explains. If you'd consider an ARM only APK (i.e. both ARMs but no x86), I could switch to that – and probably allow for 2 versions to be kept then, avoiding install/update issues whenever a new release pushes out the old one.

**Comment by michaelcspeed** [comment] 2022-05-30 10:53
Cool. Let's make new issues for those jobs then. I will close this ticket now :) 🥳

**Comment by blipp** [comment] 2022-05-30 11:55
For completeness, if I am not mistaken, the Medito app is not yet on F-Droid, that is, not yet in the official repository (see the [empty search result on f-droid.org](https://search.f-droid.org/?q=medito&lang=en)). It is in the IzzyOnDroid repository, that can be used with F-Droid (https://apt.izzysoft.de/fdroid/index/apk/meditofoundation.medito), but this repository is not used with F-Droid by default. If you are still aiming for inclusion in the official F-Droid repository (and I think that would be great), you could consider reopening this issue :)

**Comment by CodeCubeNeo** [comment] 2022-05-30 12:21
I agree, lets try to get medito in the official fdroid repositories.

**Comment by ghost** [comment] 2022-05-30 13:01
https://gitlab.com/fdroid/rfp/-/issues/1850
There is an issue open about this

**Comment by IzzySoft** [comment] 2022-06-09 07:29
> There is an issue open about this

Which is now due to be closed, as there's no progress and apart from the team's questions for updates has no activity. Cross-checking with the comments here, the main issue there was Firebase, which is now gone. So let me see what I can do "over there". Would be nice if someone from your team here could chime in there so your supporting the inclusion becomes visible :wink:

**Comment by licaon-kter** [comment] 2022-06-09 08:42
Not sure how the projects'
> You will need an API key to build the project.
> API keys are generated for regular contributors (called "volunteers")

...requirements fit [with F-Droids' one](https://f-droid.org/en/docs/Inclusion_Policy/)
> F-Droid does not sign up for any API keys. Even if provided by a third party, we include them in both, binary and sourcecode releases.

**Comment by licaon-kter** [comment] 2022-07-06 07:34
Only way this would work is if when needed you pop-up a dialogue asking for the user API key then use that.

**Comment by IzzySoft** [comment] 2022-07-06 19:19
Which BTW is what many other projects do in similar situations, and thus can count at least as "good practice" (if not even "best practice").

**Comment by parcelcat** [comment] 2023-11-02 03:20
Version 3.0 introduces a hard dependency on Google Play Services due to the app refusing to load any content if Firebase Cloud Messaging is unavailable. This regression (#581) will need to be addressed before Medito can be released on F-Droid.

**Comment by IzzySoft** [comment] 2023-11-02 08:11
May I suggest replacing FCM with @UnifiedPush? It has a Firebase distributor available as well which you could bundle with your PlayStore release – while for F-Droid, folks can pick/use the distributor of their choice (which for most will be NTFY I guess).

(Though I still wonder what a meditation app needs cloud messaging for?)

**Comment by ghost** [comment] 2023-11-13 13:20
> (Though I still wonder what a meditation app needs cloud messaging for?)

Because Charles Stross' "enshitiffication" process doesn't apply to only commercial software apparently.

**Comment by erebion** [comment] 2024-05-05 23:08
The version in @IzzySoft 's repo has stopped working a while ago, I'd love to see an updated FOSS version.

**Comment by IzzySoft** [comment] 2024-05-10 12:11
@erebion can you elaborate a little? If the app is not working anymore at all, I should remove it from IzzyOnDroid. If it's just parts of it not working (or only specific devices affected), that should at least be outlined. If a new release is pending to fix it, @michaelcspeed please say so to let us know there's no immediate action needed on our end.

**Comment by erebion** [comment] 2024-05-10 13:18
@IzzySoft It tries connecting to a server, fails, then says that it is offline. It does not work for new users. Downloaded audio can be played, but if you install it now, it is just broken and does not really do anything other than complain about being offline.

**Comment by michaelcspeed** [comment] 2024-05-10 14:28
The APIs have changed a lot since the version @IzzySoft has on their repo. We no longer support the old ones. We have no plans to release on FDroid in the near future.

**Comment by IzzySoft** [comment] 2024-05-10 14:39
Thanks for the clarification! So will there be a new release with an APK attached in the near future – or shall I rather remove the app from IzzyOnDroid, @michaelcspeed? A fresh release would solve the problem, if I understand correctly, as it would use the proper new APIs.

**Comment by erebion** [comment] 2024-05-10 15:30
Please release a new version that can be installed via F-Droid, I'd love updates, as I am sure others would.

**Comment by IzzySoft** [comment] 2024-05-10 16:48
@michaelcspeed maybe worth a try: https://support.google.com/googleplay/android-developer/contact/protectappeals

**Closed as completed** 2024-09-29 12:19 UTC
Labels: polar
