### ISSUE TITLE
[BUG] Audio streaming does not work

### ISSUE THREAD

**Issue by TailyFair** [meditohq/medito-app#279] opened 2022-08-30 09:59 UTC
**Describe the bug**
Sometimes audio streaming does not work. No matter how long I wait, exit to other windows or try different sessions, it keeps on being stuck. Unless I restart the app or download session locally and play it from local files.

**To Reproduce**
1. Happens randomly after listening to more than 1 meditation

**Expected behavior**
Audio streaming works.

**Screenshots**

https://user-images.githubusercontent.com/27275873/187445825-d3a3fb69-9fe8-4ded-8624-bee53b9c5a72.mp4

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2020
 - OS: iOS 15.6.1
 - Version 2.0.47

**Additional context**
 - Restarting app temporarily fixes the issue
 - Downloading session works

**Comment by serraojoao** [comment] 2023-02-16 15:54
facing this issue as well, however it is not a random behavior. I am always only able to listen to 1 meditation.

**Comment by michaelcspeed** [comment] 2023-04-20 16:08
Does this still happen? Maybe when we've moved to the new back end it'll avoid this issue. Would be good to test it again then

**Comment by serraojoao** [comment] 2023-04-21 10:25
> Does this still happen? Maybe when we've moved to the new back end it'll avoid this issue. Would be good to test it again then

i've just tested and could NOT reproduce it, seems to be working fine.

device: iphone 11 pro
ios: 16.3.1

**Comment by michaelcspeed** [comment] 2023-04-21 18:30
Great thanks! I'll close this and we can open it again if it happens in the future

**Closed as not planned** 2023-04-21 18:30 UTC
Labels: bug
